"""empty message

Revision ID: 4c95e5405b13
Revises: 
Create Date: 2023-12-02 13:42:11.022070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c95e5405b13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('proveedor',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_table('sucursal',
    sa.Column('id_sucursal', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id_sucursal')
    )
    op.create_table('cliente',
    sa.Column('nombre_empresa', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=50), nullable=False),
    sa.Column('codigo_producto', sa.String(length=10), nullable=True),
    sa.Column('cantidad_pedida', sa.Integer(), nullable=True),
    sa.Column('costo_total', sa.Float(), nullable=True),
    sa.Column('forma_pago', sa.String(length=30), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.PrimaryKeyConstraint('nombre_empresa')
    )
    op.create_table('materia_prima',
    sa.Column('codigo_materia', sa.String(length=10), nullable=False),
    sa.Column('nombre_materia', sa.String(length=30), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.PrimaryKeyConstraint('codigo_materia')
    )
    op.create_table('producto',
    sa.Column('codigo_producto', sa.String(length=10), nullable=False),
    sa.Column('sabor', sa.String(length=30), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.PrimaryKeyConstraint('codigo_producto')
    )
    op.create_table('telefono',
    sa.Column('id_telefono', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=15), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.PrimaryKeyConstraint('id_telefono')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('empleado',
    sa.Column('clave', sa.String(length=10), nullable=False),
    sa.Column('RFC', sa.String(length=10), nullable=False),
    sa.Column('nombres', sa.String(length=50), nullable=False),
    sa.Column('apellidos', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('sueldo', sa.Float(), nullable=False),
    sa.Column('area_laboral', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('clave'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('encargo',
    sa.Column('id_encargo', sa.Integer(), nullable=False),
    sa.Column('codigo_materia', sa.String(length=10), nullable=False),
    sa.Column('cantidad_encargo', sa.Integer(), nullable=False),
    sa.Column('cantidad_a_pagar', sa.Float(), nullable=False),
    sa.Column('forma_pago', sa.String(length=30), nullable=True),
    sa.Column('fecha_encargo', sa.Date(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_materia'], ['materia_prima.codigo_materia'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id_proveedor'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.PrimaryKeyConstraint('id_encargo')
    )
    op.create_table('imagen_materia_prima',
    sa.Column('id_images', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('rendered_data', sa.Text(), nullable=False),
    sa.Column('codigo_materia', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['codigo_materia'], ['materia_prima.codigo_materia'], ),
    sa.PrimaryKeyConstraint('id_images')
    )
    op.create_table('imagen_producto',
    sa.Column('id_images', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('rendered_data', sa.Text(), nullable=False),
    sa.Column('codigo_producto', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['codigo_producto'], ['producto.codigo_producto'], ),
    sa.PrimaryKeyConstraint('id_images')
    )
    op.create_table('imagen_empleado',
    sa.Column('id_imagenEmpleado', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('rendered_data', sa.Text(), nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['clave'], ['empleado.clave'], ),
    sa.PrimaryKeyConstraint('id_imagenEmpleado')
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.Date(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('forma_pago', sa.String(length=30), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['clave'], ['empleado.clave'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id_sucursal'], ),
    sa.PrimaryKeyConstraint('id_venta')
    )
    op.create_table('producto_vendido',
    sa.Column('id_producto_vendido', sa.Integer(), nullable=False),
    sa.Column('codigo_producto', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_producto_vendido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_vendido')
    op.drop_table('venta')
    op.drop_table('imagen_empleado')
    op.drop_table('imagen_producto')
    op.drop_table('imagen_materia_prima')
    op.drop_table('encargo')
    op.drop_table('empleado')
    op.drop_table('usuario')
    op.drop_table('telefono')
    op.drop_table('producto')
    op.drop_table('materia_prima')
    op.drop_table('cliente')
    op.drop_table('sucursal')
    op.drop_table('proveedor')
    op.drop_table('categoria')
    # ### end Alembic commands ###
